In [1]:
import pandas as pd

- - THIS IS USEFUL BECAUSE WE CAN USE THIS TO EXTRACT YEILD OF CROPS
- - By getting the temperature value , nitrogen , phosphorus , potassium we can extract yeild

In [2]:
df = pd.read_csv(r'C:\Users\HP\Desktop\XAI\DATA\Crop Yiled with Soil and Weather.csv')

In [3]:
df

      Fertilizer       temp          N          P          K      yeild
0      80.000000  28.000000  80.000000  24.000000  20.000000  12.000000
1      77.000000  27.000000  78.000000  23.000000  20.000000  12.000000
2      80.000000  26.000000  80.000000  24.000000  20.000000  12.000000
3      80.000000  28.000000  80.000000  24.000000  20.000000  12.000000
4      78.000000  27.000000  78.000000  23.000000  19.000000  12.000000
...          ...        ...        ...        ...        ...        ...
2591   78.942684  27.014634  76.838312  23.087606  20.044206  10.348503
2592   79.077362  27.153127  76.927657  23.068234  20.155436  10.528122
2593   78.986271  28.108948  77.164352  22.863654  20.989871  10.564205
2594   78.894767  28.141344  76.925149  23.071553  20.873662  10.442511
2595   79.050307  26.980865  77.124758  23.050197  19.960695  10.584638

[2596 rows x 6 columns]

In [6]:
df.columns

Index(['Fertilizer', 'temp', 'N', 'P', 'K', 'yeild'], dtype='object')

In [12]:
df[df['Fertilizer'].isna()]

Empty DataFrame
Columns: [Fertilizer, temp, N, P, K, yeild]
Index: []